[theme]
primaryColor = "#0083B8"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[server]
headless = true
runOnSave = true
port = 5000
address = "0.0.0.0"

[browser]
serverAddress = "0.0.0.0"
serverPort = 8501
gatherUsageStats = false

[global]
showWarningOnDirectExecution = false
developmentMode = false