[theme]
primaryColor = "#0083B8"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[server]
port = 8501
address = "0.0.0.0"

[browser]
serverAddress = "localhost"
serverPort = 8501
gatherUsageStats = false

[global]
showWarningOnDirectExecution = false
developmentMode = false